name: SumUp brandbook
exclude: [node_modules, gulpfile.js]

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dev

# Turns 'brand.html' into /brand \o/
permalink: pretty
